import {
    HOME_ROUTE, CHAT_ROUTE, POST_ROUTE, INFORMATION_ROUTE, FAVORITES_ROUTE, ADVERTISEMENTS_ROUTE,
    TEST_ROUTE, DATA_ROUTE, CONNECTONS_DATA_ROUTE, RICKANDMORTY_ROUTE, API_REQUEST_EXAMPLE_ROUTE, CHANNELS_ROUTE
} from "../../routes/Routes";

export const HOME_MENU_ITEM = ['Home_MENU', 'Inicio', HOME_ROUTE];

export const CHAT_MENU_ITEM = ['Chat_MENU', 'Chat', CHAT_ROUTE];

export const POST_MENU_ITEM = ['POST_MENU', 'Posts', POST_ROUTE];

export const CHANNELS_MENU_ITEM = ['CHANNELS_MENU', 'Channels', CHANNELS_ROUTE];

export const INFORMATION_MENU_ITEM = ['Information_MENU', 'Informacion', INFORMATION_ROUTE];

export const FAVORITES_MENU_ITEM = ['FAVORITES_MENU', 'Favoritos', FAVORITES_ROUTE];

export const ADVERTISEMENTS_MENU_ITEM = ['ADVERTISEMENTS_MENU', 'Anuncios', ADVERTISEMENTS_ROUTE];

export const TEST_MENU_ITEM = ['TEST_MENU', 'Test', TEST_ROUTE];

export const DATA_MENU_ITEM = ['DATA_MENU', 'Data', DATA_ROUTE];

export const CONNECTIONS_MENU_ITEM = ['CONNECTONS_MENU', 'Conexiones', CONNECTONS_DATA_ROUTE];

export const RICK_AND_MORTY_MENU_ITEM = ['RICK_AND_MORTY_MENU', 'Rick And Morty', RICKANDMORTY_ROUTE];

export const API_REQUEST_EXAMPLE_ROUTE_MENU_ITEM = ['API_REQUEST_EXAMPLE_MENU', 'Ejemplo REST', API_REQUEST_EXAMPLE_ROUTE];

export const MENU_HOME = [HOME_MENU_ITEM, CHAT_MENU_ITEM, POST_MENU_ITEM, CHANNELS_MENU_ITEM];

export const SECONDARY_MENU = [FAVORITES_MENU_ITEM, ADVERTISEMENTS_MENU_ITEM, INFORMATION_MENU_ITEM];

export const DEVELOPMENT_MENU = [TEST_MENU_ITEM, DATA_MENU_ITEM, DATA_MENU_ITEM, CONNECTIONS_MENU_ITEM, RICK_AND_MORTY_MENU_ITEM, API_REQUEST_EXAMPLE_ROUTE_MENU_ITEM];
